"""add src_dir_info table

Revision ID: 0da0ab1f1750
Revises: 3f3c30303617
Create Date: 2024-08-27 08:13:24.409706

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0da0ab1f1750"
down_revision: Union[str, None] = "3f3c30303617"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "src_dir_info",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("img_count", sa.Integer(), nullable=False),
        sa.Column(
            "raw_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("imaging_event_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["imaging_event_id"],
            ["imaging_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("event_archives", "img_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_archives",
        sa.Column("img_count", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_table("src_dir_info")
    # ### end Alembic commands ###
