"""init

Revision ID: 0e845f6803d9
Revises:
Create Date: 2024-03-06 14:43:19.458773

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e845f6803d9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prince_timestep",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("prince_position", sa.Integer(), nullable=False),
        sa.Column("img_count", sa.Integer(), nullable=False),
        sa.Column("imaging_timestamp", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prince_timestep")
    # ### end Alembic commands ###
