"""video model

Revision ID: 6c3b670fecec
Revises: c3f2bbbaa7fe
Create Date: 2024-08-08 14:33:53.252981

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c3b670fecec"
down_revision: Union[str, None] = "c3f2bbbaa7fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_params",
        sa.Column("id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("imaging_event_id", sa.Uuid(native_uuid=False), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["imaging_event_id"],
            ["imaging_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_params")
    # ### end Alembic commands ###
