"""restructure archive tables

Revision ID: 72d130e9b517
Revises: 8e4ca8eaeea7
Create Date: 2024-08-22 08:41:36.721324

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72d130e9b517"
down_revision: Union[str, None] = "8e4ca8eaeea7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "object_store_entries", ["key"])
    op.add_column(
        "data_archive_entries",
        sa.Column("job_id", sa.Uuid(native_uuid=False), nullable=True),
    )
    op.drop_column("data_archive_entries", "experiment_id")
    op.drop_column("data_archive_entries", "type")
    op.add_column(
        "data_archive_members", sa.Column("src_key", sa.String(), nullable=False)
    )
    op.drop_constraint(
        "data_archive_members_imaging_event_id_fkey",
        "data_archive_members",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "data_archive_members", "object_store_entries", ["src_key"], ["key"]
    )
    op.drop_column("data_archive_members", "imaging_event_id")
    op.drop_column("data_archive_members", "job_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_archive_members",
        sa.Column("job_id", sa.CHAR(length=32), autoincrement=False, nullable=True),
    )
    op.add_column(
        "data_archive_members",
        sa.Column(
            "imaging_event_id", sa.CHAR(length=32), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "data_archive_members", type_="foreignkey")
    op.create_foreign_key(
        "data_archive_members_imaging_event_id_fkey",
        "data_archive_members",
        "imaging_events",
        ["imaging_event_id"],
        ["id"],
    )
    op.drop_column("data_archive_members", "src_key")
    op.add_column(
        "data_archive_entries",
        sa.Column("type", sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    )
    op.add_column(
        "data_archive_entries",
        sa.Column("experiment_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("data_archive_entries", "job_id")
    op.drop_constraint(None, "object_store_entries", type_="unique")
    # ### end Alembic commands ###
