"""Remove deletion event

Revision ID: 7cbc38a986ff
Revises: 43dbc0d000fb
Create Date: 2024-07-12 08:06:52.160618

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cbc38a986ff"
down_revision: Union[str, None] = "43dbc0d000fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deletion_event")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deletion_event",
        sa.Column("id", sa.CHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "object_store_entry_id",
            sa.CHAR(length=32),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("job_id", sa.CHAR(length=32), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["object_store_entry_id"],
            ["object_store_entry.id"],
            name="deletion_event_object_store_entry_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="deletion_event_pkey"),
    )
    # ### end Alembic commands ###
