"""update src_dir_info

Revision ID: 9948b505e925
Revises: 3af106eefb24
Create Date: 2024-09-14 08:25:36.518841

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9948b505e925"
down_revision: Union[str, None] = "3af106eefb24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("src_dir_info", sa.Column("staging_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("src_dir_info", "staging_path")
    # ### end Alembic commands ###
