"""remove staging path

Revision ID: afe1cabcc32b
Revises: 9948b505e925
Create Date: 2024-10-26 11:05:06.035003

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afe1cabcc32b"
down_revision: Union[str, None] = "9948b505e925"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("src_dir_info", "staging_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "src_dir_info",
        sa.Column("staging_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
