"""remove-tables

Revision ID: d25b5aa9841d
Revises: d8543fa09f16
Create Date: 2024-11-07 15:22:07.709148

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d25b5aa9841d"
down_revision: Union[str, None] = "d8543fa09f16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("object_store_entry")
    op.drop_table("data_archive_entry")
    op.drop_table("prince_timestep")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prince_timestep",
        sa.Column(
            "timestep_id", sa.CHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.Column("experiment_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("position", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("img_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("local_dir", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("timestep_id", name="prince_timestep_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "data_archive_entry",
        sa.Column("id", sa.CHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "timestep_id", sa.CHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.Column("job_id", sa.CHAR(length=32), autoincrement=False, nullable=False),
        sa.Column("file", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("archive_path", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["timestep_id"],
            ["prince_timestep.timestep_id"],
            name="data_archive_entry_timestep_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="data_archive_entry_pkey"),
    )
    op.create_table(
        "object_store_entry",
        sa.Column("id", sa.CHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "timestep_id", sa.CHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["timestep_id"],
            ["prince_timestep.timestep_id"],
            name="object_store_entry_timestep_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="object_store_entry_pkey"),
    )
    # ### end Alembic commands ###
