"""move json fields

Revision ID: d8543fa09f16
Revises: 9948b505e925
Create Date: 2024-10-26 16:44:12.044130

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8543fa09f16"
down_revision: Union[str, None] = "9948b505e925"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "imaging_events",
        sa.Column(
            "raw_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    op.drop_column("src_dir_info", "staging_path")
    op.drop_column("src_dir_info", "raw_metadata")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "src_dir_info",
        sa.Column(
            "raw_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "src_dir_info",
        sa.Column(
            "staging_path",
            sa.VARCHAR(),
            autoincrement=False,
            server_default=sa.text("'{}'"),
            nullable=True,
        ),
    )
    op.drop_column("imaging_events", "raw_metadata")
    # ### end Alembic commands ###
