"""Remove bucket field

Revision ID: feec4cef9d55
Revises: 7cbc38a986ff
Create Date: 2024-07-19 09:03:31.045186

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "feec4cef9d55"
down_revision: Union[str, None] = "7cbc38a986ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("object_store_entry", "bucket")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "object_store_entry",
        sa.Column("bucket", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
