---
x-aws-env-variables: &aws-env-variables
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_ENDPOINT_URL: https://objectstore.surf.nl
  AWS_REGION_NAME: default
  AWS_BUCKET_NAME: ${AWS_BUCKET_NAME:-mycostreams-raw-data}"


x-sentry-env-variables: &sentry-env-variables
  SENTRY_DSN: ${SENTRY_DSN}
  SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT:-production}


x-log-labels: &log-labels
  logging: loki
  logging_jobname: ${DEPLOYMENT_NAME-:morricone}


services:
  state-manager:
    environment:
      <<: [*aws-env-variables, *sentry-env-variables]
      RABBITMQ_DSN: ${RABBITMQ_DSN}
    labels: *log-labels
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - .env
      - ../.env

  exporter:
    environment:
      <<: [*aws-env-variables, *sentry-env-variables]
    volumes:
      - prince_mount:/data/prince:ro
      - tsu_exp001_mount:/data/tsu-exp001:ro
      - tsu_exp002_mount:/data/tsu-exp002:ro
    labels: *log-labels
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - .env
      - ../.env

  purger:
    environment:
      <<: *sentry-env-variables
    volumes:
      - prince_mount:/data/prince
      - tsu_exp001_mount:/data/tsu-exp001
      - tsu_exp002_mount:/data/tsu-exp002
    labels: *log-labels
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - .env
      - ../.env

  aws-cli:
    image: amazon/aws-cli
    environment:
      <<: *aws-env-variables
      AWS_DEFAULT_REGION: default
    volumes:
      - ${POSTGRES_BACKUP_DIR:-${PWD}/backups}:/aws/postgres
    labels: *log-labels
    env_file:
      - .env
      - ../.env
    profiles:
      - tools


networks:
  traefik-public:
    external: true


volumes:
  prince_mount: 
    driver_opts:
      type: cifs
      device: //prince.amolf.nl/Data/Prince2
      o: username=${AMOLF_USERNAME},password=${AMOLF_PASSWORD}
  tsu_exp_001_mount:
  tsu_exp_002_mount:
